import { Metadata } from 'next'

export const metadata:Metadata = {
  title: 'Reddit',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      Main
    </main>
  )
}
